draperlaboratory/VIBES

bap-vibes/src/arm_selector.ml, bap-vibes/tests/unit/test_arm_selector.ml
It turns out that with `.syntax unified` the assembler can figure out whether to use the wide or narrow encoding in Thumb mode.
=> Remove use of `addw` from the selector

bap-vibes/src/bir_passes.ml, bap-vibes/src/data.ml, bap-vibes/src/data.mli, bap-vibes/src/kb_error.ml, bap-vibes/src/kb_error.mli, bap-vibes/src/patch_ingester.ml, bap-vibes/src/pipeline.ml, bap-vibes/src/seeder.ml, bap-vibes/tests/integration/patches.ml, bap-vibes/tests/integration/test_minizinc.ml, bap-vibes/tests/unit/patches.ml, bap-vibes/tests/unit/test_compiler.ml, bap-vibes/tests/unit/test_patch_ingester.ml, resources/exes/thumb-no-verification/config.json, resources/exes/thumb-no-verification/loader.ogre, resources/exes/thumb-patch-space/config.json, resources/exes/thumb-patch-space/loader.ogre, resources/exes/thumb-simple-compiled/config.json, resources/exes/thumb-simple-compiled/loader.ogre, resources/exes/thumb-simple-multi/config.json, resources/exes/thumb-simple-multi/loader.ogre
This partially fixes the failing tests/bitrot that has happened with recent changes to BAP.
1. We create a property for `Theory.Program.cls` that holds the semantics for the patch program, and then we register a promise to provide this semantics for `Theory.Semantics.cls` . For all program labels that we didn't create specifically for each patch object, this semantics will be empty, so we can avoid any conflicts. @jtpaasch  had this fixed in #204, so I apologize for stealing his thunder in this PR.
2. The skipped test in `test_compiler` is now fixed and it passes.
3. All but one of the system tests are fixed. The Thumb system tests seemed to suffer from program labels having the `:unknown` encoding, perhaps due to a recent change in BAP. To fix this, we manually provide the OGRE file to …
=> Fixes bitrot (partially)

bap-vibes/src/arm_selector.ml, bap-vibes/tests/unit/test_arm_selector.ml, bap-vibes/tests/unit/test_parse_c.ml
It seems that after https://github.com/BinaryAnalysisPlatform/bap/pull/1499 the BIL/BIR being reified from the Core Theory terms had some rewriting/optimization done on it.
Previously in https://github.com/draperlaboratory/VIBES/pull/178 I worked to make the C semantics explicit such that:
```
if (!x) {
y = 4;
}
```
will lower to the following BIL:
```
if (x = 0) {
y := 4
}
```
But now it seems that this has been undone and it now just applies a logical NOT. The tests have been fixed to reflect this.
=> Fixes tests for latest BAP

plugin/lib/vibes_plugin_errors.ml, plugin/lib/vibes_plugin_errors.mli, plugin/lib/vibes_plugin_parameters.ml
In some cases we want to tell WP to initialize the read-only memory in the binary, so this provides a field in the config file to do exactly that.
Also, the plugin should be passing the OGRE specification as a filename to WP instead of the actual string contents of the file. Thus, if the BSI metadata field is populated, then we will need to create a temporary file to store the generated OGRE information.
=> Adds support for the `init-mem` option in the `wp-params`

bap-vibes/src/patch_c.ml, bap-vibes/src/pipeline.ml, bap-vibes/src/verifier.ml, bap-vibes/src/verifier.mli, bap-vibes/tests/integration/test_minizinc.ml, bap-vibes/tests/unit/helpers.ml, bap-vibes/tests/unit/test_parse_c.ml, bap-vibes/tests/unit/test_substituter.ml, resources/exes/arm-isel-jmp2/config.json, resources/exes/arm-simple-sum/config.json
If we're enabling `init-mem` then we need to use the provided utility in `Bap_wp` to collect the known code regions of both binaries.
=> Fix compatibility with WP `init-mem` parameter

bap-vibes/src/arm_selector.ml, bap-vibes/src/bir_passes.ml, bap-vibes/src/config.ml, bap-vibes/src/config.mli, bap-vibes/src/core_c.ml, bap-vibes/src/data.ml, bap-vibes/src/data.mli, bap-vibes/src/ir.ml, bap-vibes/src/kb_error.ml, bap-vibes/src/kb_error.mli, bap-vibes/src/linear_ssa.ml, bap-vibes/src/linear_ssa.mli, bap-vibes/src/minizinc.ml, bap-vibes/src/patch_c.ml, bap-vibes/src/patcher.ml, bap-vibes/src/patcher.mli, bap-vibes/src/pipeline.ml, bap-vibes/src/seeder.ml, bap-vibes/src/utils.ml, bap-vibes/src/utils.mli, bap-vibes/tests/unit/test_arm_selector.ml, bap-vibes/tests/unit/test_linear_ssa.ml, bap-vibes/tests/unit/test_patcher.ml, plugin/lib/vibes_plugin_parameters.ml, resources/exes/arm-bounds-check/config.json, resources/exes/arm-branch/config.json, resources/exes/arm-patch-call/config.json, resources/exes/thumb-patch-space/config.json
1. The current instruction selector was ignoring the return destination, e.g.: `call x with return %00001234`, hoping that `blk00001234` is the immediate next block in the generated assembly code.  I've run into a case where this assumption is broken, so we'll now insert an explicit branch to this location, hoping that the peephole optimizer can get rid of it later.
2. `Linear_ssa.orig_name` was incorrectly rejecting variable names with underscores in them, so if you wanted to refer to them in, say, the extra Minizinc constraints, then they wouldn't appear there.
3. The patcher should output the inferred sizes of each patch, by name. Feels right to inform the user about it.
4. The handling of constant integers in the C frontend needed some fixing. By default, they are the same size as …
=> More miscellaneous fixes

vibes-tools/resources/patch.2.bir, vibes-tools/resources/patch.2.opt.bir, vibes-tools/resources/patch.bir, vibes-tools/resources/patch.opt.bir, vibes-tools/tools/vibes-serializers/lib/bir.ml
When they're littered throughout the program terms it tends to make the serialized output unreadable, which goes against a major design goal we have.
We still have the ugly UUID strings, but at least they're separated from the part that the user may be hand-editing.
=> Moves the attributes to a separate section when serializing

vibes-tools/tools/vibes-opt/lib/shape.ml, vibes-tools/tools/vibes-patch-info/lib/types.ml, vibes-tools/tools/vibes-patch-info/lib/types.mli, vibes-tools/tools/vibes-patch/lib/patcher.ml
It's more natural to use hex notation in JSON to describe these fields, but JSON doesn't support it, so we need to use a different datatype.
=> Use the bitvector type for patch space addresses

vibes-tools/resources/example-as-2.bash, vibes-tools/resources/example-as.bash, vibes-tools/resources/example-opt-2.bash, vibes-tools/resources/example-opt.bash, vibes-tools/resources/example-parse-2.bash, vibes-tools/resources/example-parse.bash, vibes-tools/resources/example-select-2.bash, vibes-tools/resources/example-select.bash, vibes-tools/resources/patch.asm, vibes-tools/tools/vibes-as/lib/dune, vibes-tools/tools/vibes-as/lib/opt.ml, vibes-tools/tools/vibes-c-toolkit/lib/patch_c.ml, vibes-tools/tools/vibes-ir/lib/types.ml, vibes-tools/tools/vibes-ir/lib/types.mli, vibes-tools/tools/vibes-minizinc/lib/types.ml, vibes-tools/tools/vibes-opt/lib/opt.ml, vibes-tools/tools/vibes-patch/bin/main.ml
1. The check for target matching `arm` in `Patch_c` is wrong.
2. The optimization for removing empty blocks should only happen for those blocks that are unreferenced (e.g. it is the target of a jump).
3. The calculation of the `width` parameter for the MiniZinc model was wrong, leading to incorrect solutions.
=> Miscellaneous fixes to `vibes-tools`

vibes-tools/tools/vibes-as/lib/arm/arm_printer.ml, vibes-tools/tools/vibes-as/lib/types.ml, vibes-tools/tools/vibes-as/lib/types.mli, vibes-tools/tools/vibes-higher-vars/lib/substituter.ml, vibes-tools/tools/vibes-init/lib/types.ml, vibes-tools/tools/vibes-patch-info/lib/types.ml, vibes-tools/tools/vibes-patch-info/lib/types.mli, vibes-tools/tools/vibes-patch/lib/arm/arm_utils.ml, vibes-tools/tools/vibes-patch/lib/errors.ml, vibes-tools/tools/vibes-patch/lib/patcher.ml, vibes-tools/tools/vibes-patch/lib/types.ml, vibes-tools/tools/vibes-patch/lib/types.mli
Some patches require us to only insert new code, which means we will have to overwrite some instructions that are needed by the program.
The user can tell us this with the `overwrite` field in the patch info config file. If it's `false` (default `true`) then any instructions that would be overwritten should be inserted at the end of the patch code.
We don't do any analysis on the function being patched, so it's up to the user to specify the necessary constraints (such as in the patch vars) on what registers and so on are needed by such instructions.
=> Preserve overwritten instructions if the user tells us to

resources/minizinc/model.mzn, vibes-tools/resources/patch.2.asm, vibes-tools/resources/patch.asm, vibes-tools/tools/vibes-as/lib/arm/arm_printer.ml, vibes-tools/tools/vibes-ir/lib/types.ml, vibes-tools/tools/vibes-minizinc/lib/errors.ml, vibes-tools/tools/vibes-minizinc/lib/types.ml, vibes-tools/tools/vibes-select/lib/arm/arm_ops.ml, vibes-tools/tools/vibes-select/lib/arm/arm_ops.mli, vibes-tools/tools/vibes-select/lib/arm/arm_selector.ml
Currently we don't generate optional copy instructions and in fact we do this optimization prematurely in the instruction selector, but we could make room for it in the future.
Additionally, I made some adjustments to the MiniZinc model that seems to produce better results.
=> Adjust model + add some code for optional copy instructions

vibes-tools/docs/tutorial/Tutorial.md, vibes-tools/tools/vibes-as/lib/solver.ml, vibes-tools/tools/vibes-c-toolkit/lib/patch_c.ml, vibes-tools/tools/vibes-common-cli-options/lib/language.ml, vibes-tools/tools/vibes-common-cli-options/lib/language.mli, vibes-tools/tools/vibes-init/bin/main.ml, vibes-tools/tools/vibes-init/lib/errors.ml, vibes-tools/tools/vibes-init/lib/runner.ml, vibes-tools/tools/vibes-init/lib/runner.mli, vibes-tools/tools/vibes-init/lib/types.ml, vibes-tools/tools/vibes-init/lib/types.mli, vibes-tools/tools/vibes-minizinc/lib/types.ml, vibes-tools/tools/vibes-patch/lib/errors.ml, vibes-tools/tools/vibes-patch/lib/patcher.ml, vibes-tools/tools/vibes-select/lib/selector.ml, vibes-tools/tools/vibes-utils/lib/core_theory.ml, vibes-tools/tools/vibes-utils/lib/core_theory.mli, vibes-tools/tools/vibes-utils/lib/dune, vibes-tools/tools/vibes-utils/lib/errors.ml, vibes-tools/tools/vibes-utils/lib/loader.ml, vibes-tools/tools/vibes-utils/lib/loader.mli
The user can still provide the language if our heuristic gets it wrong. Also fixes checks for `Arm_target.parent`, since we should also check if it's 32-bit ARM (we don't support 64-bit ARM).
Additionally, the MiniZinc backend shouldn't be considering floating point registers right now, which should cut down on solving time.
=> Infer the target and language from the binary in `vibes-init`

vibes-tools/resources/binja/ogre.py, vibes-tools/resources/binja/patchinfo.py
When we collect the live variables, we should try to use the "Mapped Medium Level IL" when possible. There's other fixes in here that cover some edge cases that I'm discovering.
=> Some fixes to Binja higher vars

vibes-tools/tools/vibes-patch/lib/arm/arm_utils.ml, vibes-tools/tools/vibes-patch/lib/dune, vibes-tools/tools/vibes-patch/lib/errors.ml, vibes-tools/tools/vibes-patch/lib/patcher.ml, vibes-tools/tools/vibes-patch/lib/types.ml, vibes-tools/tools/vibes-patch/lib/types.mli, vibes-tools/tools/vibes-patch/lib/utils.ml, vibes-tools/tools/vibes-patch/lib/utils.mli
As an alternative to the user-provided external patch spaces, it turns out that we can do a minimally-invasive edit to the program header entry of the main code segment, i.e. simply extending its size.  The inspiration came from this Binary Ninja plugin I found: https://github.com/jeffli678/bnhook/blob/master/hookmanager.py#L76
I've observed that there is a decent amount of space between the end of the code segment and the next segment that gets loaded into memory (usually the data segment). The biggest surprise to me is that this technique actually works for how simple it is.
=> Try extending the ELF code segment in `vibes-patch`

vibes-tools/tools/vibes-c-toolkit/lib/parse_c.ml, vibes-tools/tools/vibes-opt/lib/shape.ml, vibes-tools/tools/vibes-parse/lib/runner.ml
1. Allow empty C file as input to `vibes-parse`
2. Show line and column numbers when the C parser fails
3. Fix case in branch relaxation where there is no patch spaces and the patch size is 0. Our solution to this problem is still hacky and I don't like it.
=> More fixes

vibes-tools/resources/binja/patcheditor.py, vibes-tools/tools/vibes-common-cli-options/lib/ogre.ml, vibes-tools/tools/vibes-common-cli-options/lib/ogre.mli, vibes-tools/tools/vibes-init/bin/main.ml, vibes-tools/tools/vibes-init/lib/runner.ml, vibes-tools/tools/vibes-init/lib/runner.mli, vibes-tools/tools/vibes-init/lib/types.ml, vibes-tools/tools/vibes-init/lib/types.mli, vibes-tools/tools/vibes-patch-info/lib/types.mli, vibes-tools/tools/vibes-patch/bin/main.ml, vibes-tools/tools/vibes-patch/lib/arm/arm_utils.ml, vibes-tools/tools/vibes-patch/lib/patcher.ml, vibes-tools/tools/vibes-patch/lib/patcher.mli, vibes-tools/tools/vibes-patch/lib/runner.ml, vibes-tools/tools/vibes-patch/lib/runner.mli, vibes-tools/tools/vibes-patch/lib/types.ml, vibes-tools/tools/vibes-patch/lib/types.mli, vibes-tools/tools/vibes-patch/lib/utils.ml, vibes-tools/tools/vibes-patch/lib/utils.mli
When we place the patches in the binary, we may encounter the following scenarios:
1. We used an external patch space (which may or may not have previously existed).
2. The patch contains some inline data.
In either case, the OGRE file may not have this information, which is bad for when we want to do verification. Previously, this would be done manually, but obviously it's not a great user experience. This PR makes it so that we can extend the existing OGRE specification (if the user provided it to us) with this information, automatically.
=> Have `vibes-patch` output the modified OGRE file

vibes-tools/tools/vibes-c-toolkit/lib/core_c.ml, vibes-tools/tools/vibes-c-toolkit/lib/ctype.ml, vibes-tools/tools/vibes-c-toolkit/lib/ctype.mli, vibes-tools/tools/vibes-c-toolkit/lib/errors.ml, vibes-tools/tools/vibes-c-toolkit/lib/parse_c.ml, vibes-tools/tools/vibes-c-toolkit/lib/parse_c.mli, vibes-tools/tools/vibes-c-toolkit/lib/patch_c.ml, vibes-tools/tools/vibes-c-toolkit/lib/patch_c.mli, vibes-tools/tools/vibes-parse/lib/errors.ml, vibes-tools/tools/vibes-parse/lib/runner.ml
Addresses #173. To better support the C type system we re-use the code from the `Bap_c` module, which required a bit of refactoring.
Also, the error messages from the C parser are improved.
=> Refactor C frontend again

vibes-tools/tools/vibes-c-toolkit/lib/core_c.ml, vibes-tools/tools/vibes-c-toolkit/lib/ctype.ml, vibes-tools/tools/vibes-c-toolkit/lib/patch_c.ml
It turns out that BAP indeed has done a lot of the heavy lifting for us (in particular with `Bap_c_abi.layout`). It doesn't take that much more work to support `struct`s in a minimal way.
=> Minimal support for `struct` types

vibes-tools/resources/binja/db.py, vibes-tools/resources/binja/ogre.py, vibes-tools/resources/binja/utils.py, vibes-tools/tools/vibes-patch/lib/patcher.ml
The bookkeeping for the current set of patches and user-specified spaces was broken.
Also, when we provide a `segment` attribute in OGRE, we need to also provide a `named-region` for it to make BAP's image loader happy.
=> Fix generating OGRE segments + fix deleting manual spaces in plugin

vibes-tools/tools/vibes-as/lib/dune, vibes-tools/tools/vibes-bir/lib/dune, vibes-tools/tools/vibes-c-toolkit/lib/dune, vibes-tools/tools/vibes-higher-vars/lib/dune, vibes-tools/tools/vibes-init/lib/dune, vibes-tools/tools/vibes-init/lib/runner.ml, vibes-tools/tools/vibes-init/lib/types.ml, vibes-tools/tools/vibes-init/lib/types.mli, vibes-tools/tools/vibes-ir/lib/dune, vibes-tools/tools/vibes-linear-ssa/lib/dune, vibes-tools/tools/vibes-minizinc/lib/dune, vibes-tools/tools/vibes-opt/lib/dune, vibes-tools/tools/vibes-parse/lib/dune, vibes-tools/tools/vibes-patch-info/lib/dune, vibes-tools/tools/vibes-patch/lib/dune, vibes-tools/tools/vibes-playground/bin/dune, vibes-tools/tools/vibes-select/lib/dune, vibes-tools/tools/vibes-serializers/lib/dune, vibes-tools/tools/vibes-utils/lib/dune
BAP is using dune by default now, so we need to make some slight changes to our build process.
=> Fixes for BAP dune

vibes-tools/Makefile, vibes-tools/tools/Makefile, vibes-tools/tools/vibes-as/test/dune, vibes-tools/tools/vibes-as/test/test_arm.ml, vibes-tools/tools/vibes-c-toolkit/lib/patch_c.ml, vibes-tools/tools/vibes-c-toolkit/test/dune, vibes-tools/tools/vibes-c-toolkit/test/test_core.ml, vibes-tools/tools/vibes-c-toolkit/test/test_parse.ml, vibes-tools/tools/vibes-higher-vars/test/dune, vibes-tools/tools/vibes-higher-vars/test/test_substituter.ml, vibes-tools/tools/vibes-ir/test/dune, vibes-tools/tools/vibes-ir/test/test_ir.ml, vibes-tools/tools/vibes-linear-ssa/test/dune, vibes-tools/tools/vibes-linear-ssa/test/test_linear_ssa.ml, vibes-tools/tools/vibes-opt/test/dune, vibes-tools/tools/vibes-opt/test/test_opt.ml
This is mostly a direct port of the unit tests from `bap-vibes` to the new `vibes-tools` code.
=> Restore most of the unit tests for vibes-tools

resources/binja/ogre.py, resources/binja/patcheditor.py, resources/binja/patchinfo.py, resources/binja/utils.py, resources/binja/vars.py, tools/vibes-c-toolkit/lib/core_c.ml, tools/vibes-opt/lib/opt.ml, tools/vibes-patch/lib/patcher.ml, tools/vibes-patch/lib/utils.ml, tools/vibes-patch/lib/utils.mli
1. In `Core_c` we weren't giving the correct sort to constant integers.
2. When we can't find the correct HLIL mapping for the end address of the patch, we can look to see in the rest of the block if such a mapping exists, and if not, traverse the dominator tree for the first match. This also fixes the case where we just cannot find any HLIL mappings.
3. For now, we will avoid providing functions in the higher variables that differ from whatever encoding Binary Ninja told us the binary has (e.g. if the binary is the `thumb2` arch, then don't allow `armv7` functions). Meanwhile, we take advantage of the `symbol-value` attribute in OGRE to mark functions as using either ARM or Thumb encodings.
=> More fixes for latest challenge problem

tools/vibes-minizinc/lib/types.ml
This register is generally used as the small area data pointer, which is similar to the GP register in MIPS. We should avoid overwriting it in patches.
=> Exclude R13 for PowerPC

tools/vibes-opt/lib/opt.ml, tools/vibes-opt/lib/opt.mli
The handling of short-circuiting boolean `&&` and `||` in our C front-end generates correct but naive code. Take for example the following program from our testsuite:
```
{
int *a, i, retval;
if (i < 3 && i >= 0) {
retval = a[i];
} else {
retval = -1;
}
}
```
This gets compiled to the following BIL code:
```
{
#0 := i <$ 3
if (#0 <> 0) {
#0 := 0 <=$ i
}
if (#0 <> 0) {
retval := mem[a + 4 * i, el]:u32
}
else {
retval := 0xFFFFFFFF
}
}
```
We're carrying the result of each condition of the `&&` in the virtual variable `#0`, which is never used anywhere except in the final `if` statement. Unsurprisingly, the generated assembly for this is highly unoptimal (especially in terms of size). The corresponding BIR code:
```
0000001e: sub bounds-check.bir()
0000001b:
00000021: i := reg:R1
00000022: …
```
=> Optimize BIR code when we have short-circuiting conditionals
